#!/bin/zsh
# Sync Examples/RecipesV3/.env → local.xcconfig + bundleable RecipesV3.env (APP_ID only).
# Source of truth for live Instant is the gitignored .env file.
set -euo pipefail

script_dir="${0:A:h}"
env_file="${RECIPES_V3_ENV_PATH:-$script_dir/.env}"
local_xcconfig="$script_dir/RecipesV3.local.xcconfig"
bundle_env="$script_dir/RecipesV3.env"
private_env="${INSTANT_RECIPES_CREDENTIAL_DIR:-${script_dir:h:h:h}/private/credentials/swift-instant-data}/recipes-v3.env"

if [[ ! -s "$env_file" && -s "$private_env" ]]; then
  env_file="$private_env"
fi

if [[ ! -s "$env_file" ]]; then
  print -u2 "Missing $script_dir/.env (or private recipes-v3.env)."
  print -u2 "Copy .env.example → .env and set INSTANT_APP_ID, or run ./provision-live-app.sh"
  exit 1
fi

app_id="$(sed -n 's/^[[:space:]]*INSTANT_APP_ID=//p' "$env_file" | head -1 | tr -d '\"' | tr -d "'" | tr -d '[:space:]')"
if [[ ! "$app_id" =~ ^[0-9a-fA-F-]{36}$ ]]; then
  print -u2 "INSTANT_APP_ID missing or not a UUID in $env_file"
  exit 1
fi

umask 077
printf 'INSTANT_APP_ID = %s\n' "$app_id" >"$local_xcconfig"
chmod 600 "$local_xcconfig"

# Bundle-safe only — never write admin tokens into the app package.
{
  print "# Generated by sync-env.sh from .env — APP_ID only (safe to embed)."
  print "INSTANT_APP_ID=$app_id"
} >"$bundle_env"
chmod 600 "$bundle_env"

print "Synced live Instant app id ${app_id:0:8}… → RecipesV3.local.xcconfig + RecipesV3.env"
