#!/usr/bin/env python3
"""Generate clean-Git build provenance for compilation or resource embedding."""

from __future__ import annotations

import argparse
import datetime as dt
import json
import os
from pathlib import Path
import platform
import socket
import subprocess
import tempfile


def git(repo: Path, *args: str) -> str:
    result = subprocess.run(
        ["git", "-C", str(repo), *args],
        check=True,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    return result.stdout.strip()


def git_optional(repo: Path, *args: str) -> str:
    result = subprocess.run(
        ["git", "-C", str(repo), *args],
        check=False,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
    )
    return result.stdout.strip() if result.returncode == 0 else ""


def ordinal(day: int) -> str:
    if 10 < day % 100 < 14:
        suffix = "th"
    else:
        suffix = {1: "st", 2: "nd", 3: "rd"}.get(day % 10, "th")
    return f"{day}{suffix}"


def human_local_time(value: dt.datetime) -> str:
    hour = value.hour % 12 or 12
    meridiem = "a.m." if value.hour < 12 else "p.m."
    zone = value.tzname() or value.strftime("%z")
    return (
        f"{value.strftime('%B')} {ordinal(value.day)}, {value.year} at "
        f"{hour}:{value.minute:02d}:{value.second:02d} {meridiem} {zone}"
    )


def render(payload: dict[str, object], output_format: str) -> str:
    pretty = json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False)
    if output_format == "json":
        return pretty + "\n"
    if output_format == "swift":
        return (
            "// Generated by build_provenance.py. Do not edit.\n"
            "public enum BuildProvenance {\n"
            "  public static let json = #\"\"\"\n"
            f"{pretty}\n"
            "\"\"\"#\n"
            "}\n"
        )
    if output_format == "typescript":
        return (
            "// Generated by build_provenance.py. Do not edit.\n"
            f"export const buildProvenance = {pretty} as const;\n"
        )
    compact = json.dumps(payload, separators=(",", ":"), ensure_ascii=False)
    return (
        "/* Generated by build_provenance.py. Do not edit. */\n"
        "#ifndef BUILD_PROVENANCE_GENERATED_H\n"
        "#define BUILD_PROVENANCE_GENERATED_H\n"
        f"#define BUILD_PROVENANCE_JSON {json.dumps(compact)}\n"
        "#endif\n"
    )


def atomic_write(path: Path, value: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{path.name}.", dir=str(path.parent), text=True
    )
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
            handle.write(value)
        os.chmod(temporary_name, 0o644)
        os.replace(temporary_name, path)
    except BaseException:
        try:
            os.unlink(temporary_name)
        except FileNotFoundError:
            pass
        raise


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo", type=Path, default=Path.cwd())
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument(
        "--format",
        choices=("json", "swift", "typescript", "c-header"),
        default="json",
    )
    parser.add_argument("--artifact-location", type=Path, required=True)
    parser.add_argument("--project-name")
    parser.add_argument("--version")
    parser.add_argument("--build-number")
    parser.add_argument("--configuration")
    parser.add_argument("--platform")
    parser.add_argument("--architecture")
    args = parser.parse_args()

    repo = Path(git(args.repo, "rev-parse", "--show-toplevel")).resolve()
    output = args.output.expanduser().resolve()
    try:
        relative_output = output.relative_to(repo)
    except ValueError:
        relative_output = None
    if relative_output is not None:
        relative = str(relative_output)
        tracked = bool(git_optional(repo, "ls-files", "--error-unmatch", "--", relative))
        ignored = subprocess.run(
            ["git", "-C", str(repo), "check-ignore", "--quiet", "--", relative],
            check=False,
        ).returncode == 0
        if tracked or not ignored:
            raise SystemExit(
                "provenance output inside the repository must be untracked and ignored; "
                f"use an ignored generated directory or an external build directory: {output}"
            )

    dirty_lines = git(repo, "status", "--porcelain=v1", "--untracked-files=all")
    if dirty_lines:
        preview = "\n".join(dirty_lines.splitlines()[:20])
        raise SystemExit(
            "refusing to generate reproducible-build provenance from a dirty tree:\n"
            + preview
        )

    now = dt.datetime.now().astimezone().replace(microsecond=0)
    commit = git(repo, "rev-parse", "HEAD")
    branch = git_optional(repo, "symbolic-ref", "--quiet", "--short", "HEAD") or "DETACHED"
    artifact = args.artifact_location.expanduser().resolve()
    version = args.version or os.environ.get("MARKETING_VERSION")
    build_number = args.build_number or os.environ.get("CURRENT_PROJECT_VERSION")
    configuration = args.configuration or os.environ.get("CONFIGURATION")
    target_platform = (
        args.platform or os.environ.get("PLATFORM_NAME") or platform.system()
    )
    architecture = args.architecture or os.environ.get("ARCHS") or platform.machine()
    build_details = {
        "version": version,
        "buildNumber": build_number,
        "configuration": configuration,
        "platform": target_platform,
        "architecture": architecture,
    }
    payload: dict[str, object] = {
        "schemaVersion": 1,
        "projectName": args.project_name or repo.name,
        "git": {
            "commit": commit,
            "shortCommit": git(repo, "rev-parse", "--short=12", commit),
            "subject": git(repo, "show", "-s", "--format=%s", commit),
            "describe": git_optional(repo, "describe", "--always", "--tags", commit),
            "branch": branch,
            "dirty": False,
        },
        "build": {
            "timestampLocal": human_local_time(now),
            "timestampISO8601": now.isoformat(),
            "timezone": now.tzname() or now.strftime("%z"),
            "host": socket.gethostname(),
            "sourceRoot": str(repo),
            "artifactLocation": str(artifact),
            "generatedProvenanceLocation": str(output),
            **{key: value for key, value in build_details.items() if value},
        },
    }
    atomic_write(output, render(payload, args.format))
    print(f"Generated {args.format} provenance for {commit} at {output}")


if __name__ == "__main__":
    main()
